version: "3"
services:
  nosql-db:
    image: mongo
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    container_name: nosql-db
    ports: 
      - 27017:27017
    volumes:
      - ./db/:/data/db

  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    ports:
      - '5672:5672'

  products:
    build:
      dockerfile: Dockerfile
      context: ./products
    image: smartx.azurecr.io/products:latest
    container_name: products
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - "nosql-db"
      - "rabbitmq"
    volumes:
      - .:/app
      - /app/products/node_modules

    env_file:
      - ./products/.env.dev
  shopping:
    build:
      dockerfile: Dockerfile
      context: ./shopping
    image: smartx.azurecr.io/shopping:latest
    container_name: shopping
    environment:
      MONGODB_URI: mongodb://nosql-db:27017/shoppings
    ports:
      - "8003:8003"
    restart: always
    depends_on:
      - "nosql-db"
      - "rabbitmq"
    volumes:
      - .:/app
      - /app/shopping/node_modules
    env_file:
      - ./shopping/.env.dev
  customer:
    build:
      dockerfile: Dockerfile
      context: ./customer
    image: smartx.azurecr.io/customer:latest
    container_name: customer
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - "nosql-db"
      - "rabbitmq"
    volumes:
      - .:/app/
      - /app/customer/node_modules
    env_file:
      - ./customer/.env.dev
  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    image: smartx.azurecr.io/nginx-proxy:latest
    depends_on:
      - products
      - shopping
      - customer
    ports:
      - 80:80
